### ISSUE TITLE
platzi-js-basico/reto-objetos-y-funcion-constructora.html

### ISSUE THREAD

**Issue by CarlosNaveda** [hijuliancode/platzi-js-basico#1]
Archivo: platzi-js-basico/reto-objetos-y-funcion-constructora.html
Detalle: Hola, corrí tu script, pero no devolvió los 30 carros del reto, entiendo que hay que hacer un loop más largo, porque me salió solo esto:
<img width="1508" alt="Captura de Pantalla 2020-05-05 a la(s) 07 49 21" src="https://user-images.githubusercontent.com/51273439/81067939-1d448800-8ea5-11ea-8df2-096f4e92df75.png">

**Comment by hijuliancode** [comment]
Hola Carlos, sí, tienes razón, este solo devuelve 3.

Podría devolver 2, 3, **30**, o incluso más, depende del tamaño del array, en este caso solo deje 3 para no hacer el código de ejemplo tan largo. 

![Captura de Pantalla 2020-05-07 a la(s) 8 31 52 p  m](https://user-images.githubusercontent.com/64325884/81360544-cc4db300-90a1-11ea-85f1-83ceb86a1781.png)

**Comment by CarlosNaveda** [comment]
comprendo.
